### ISSUE TITLE
Rename the config file

### ISSUE THREAD

**Issue by nouiz** [rdevon/cortex#119]
Right now, it is ~/config.yml. This name is too generic. It could conflict with other software. Also, user won't easily know for which software this file is.

I propose ~/.cortex.yml instead. It make it clear to the user this is a file related to cortex. I'll also make this an "invisible" file as all the configuration file. This is 2 standards on Linux.

**Comment by rdevon** [comment]
I'm for this. But currently there appears to be an issue with moving the config file outside of the repo? #115
