### ISSUE TITLE
Visdom server detection

### ISSUE THREAD

**Issue by rdevon** [rdevon/cortex#121]
Some feedback for the user would help if the visdom server isn't running. What should be added is a simple script which checks if a server is running with the visualization object is created. If it's not, allow the user to opt to start a server at the location specified in the config, try another location, or skip visualization.

**Comment by joeljpoulin** [comment]
I have a visdom server locally running on http://localhost:8097. I did configuration and ran an experiment with `cortex GAN --d.source CIFAR10 --d.copy_to_local`. Experiment is running correctly (no output errors & no output errors related to visdom. There is nothing showed in visdom though. I'm on the dev branch. Is visdom suppose to work on this branch?

**Comment by joeljpoulin** [comment]
@rdevon
There is when a Visdom server is being instantiated. 
```
def init(viz_config):
    global visualizer, config_font
    if viz_config is not None and ('server' in viz_config.keys() or
                                   'port' in viz_config.keys()):
        server = viz_config.get('server', None)
        port = viz_config.get('port', 8097)
        visualizer = visdom.Visdom(server=server, port=port)
        logger.info('Using visdom server at {}({})'.format(server, port))
    else:
        visualizer = visdom.Visdom()
        logger.info('Using local visdom server')
    config_font = viz_config.get('font')
```
When you say 
>  which checks if a server is running with the visualization object is created

Do you mean looking at the default Visdom server address (http://localhost:8097/) if there is already a server up ? Or look for the address given in the `.config.yml` file if there's a server up? Or look at both, and after give the user the option to start the visualization or skip it?
