### ISSUE TITLE
Argparsing needs to be tested thoroughly 

### ISSUE THREAD

**Issue by rdevon** [rdevon/cortex#141]
The hyperparameters of a model are set in many ways in cortex:

1) default arguments in build, routine, visualize, etc
2) through a defaults static attribute for a model
3) through the command line.

All of these need to be tested. Notably, we need to make sure that:

the defaults for the build, routine, visualize, etc are the default and these show up in the command line.
the above can be overridden by the defaults static attribute.
The command line can override the above
Nested arguments (within dicts) are updated corrected. In other words, if a default argument looks like this:
`classifier_args = dict(batch_size=False)`

Updating this argument with `classifier_args=dict(dim_h=100)` yields 
`classifier_args = dict(batch_size=False, dim_h=100)`

So far everything *looks* like it's working, but it needs to be tested.

**Comment by joeljpoulin** [comment]
Resolve in PR #162.
