### ISSUE TITLE
Reloading with old arguments

### ISSUE THREAD

**Issue by rdevon** [rdevon/cortex#166]
`-r <PATH>` isn't loading the model arguments, so they have to be all reentered for reloading to work properly. This should be fixed ASAP and tested.

**Comment by joeljpoulin** [comment]
So, we should save the arguments from the first run and save it in the .t7 files?

**Comment by rdevon** [comment]
So the arguments *should* be saved (we've used this feature often to double check our models), but it's not being used in the new model.
